<?php

return [
    'Cabe' => [
        'name' => 'Cabe',
        'slug' => 'Cabe',
        'humidity' => '60-80%',
        'temperature' => '21-27°C',
        'light' => '60-85%',
        'tds' => '1400-2100 ppm',
        'pump' => '5-10 detik',
        'thresholds' => [
            'humidity_min' => 60,
            'humidity_max' => 80,
            'temperature_min' => 21,
            'temperature_max' => 27,
            'light_min' => 60,
            'light_max' => 85,
            'tds_min' => 1400,
            'tds_max' => 2100,
            'pump_seconds_min' => 5,
            'pump_seconds_max' => 10,
        ],
    ],
    'Tomat' => [
        'name' => 'Tomat',
        'slug' => 'Tomat',
        'humidity' => '60-75%',
        'temperature' => '21-27°C',
        'light' => '65-90%',
        'tds' => '1400-2500 ppm',
        'pump' => '7-12 detik',
        'thresholds' => [
            'humidity_min' => 60,
            'humidity_max' => 75,
            'temperature_min' => 21,
            'temperature_max' => 27,
            'light_min' => 65,
            'light_max' => 90,
            'tds_min' => 1400,
            'tds_max' => 2500,
            'pump_seconds_min' => 7,
            'pump_seconds_max' => 12,
        ],
    ],
    'Seledri' => [
        'name' => 'Seledri',
        'slug' => 'Seledri',
        'humidity' => '70-85%',
        'temperature' => '15-23°C',
        'light' => '45-70%',
        'tds' => '1260-1680 ppm',
        'pump' => '5-8 detik',
        'thresholds' => [
            'humidity_min' => 70,
            'humidity_max' => 85,
            'temperature_min' => 15,
            'temperature_max' => 23,
            'light_min' => 45,
            'light_max' => 70,
            'tds_min' => 1260,
            'tds_max' => 1680,
            'pump_seconds_min' => 5,
            'pump_seconds_max' => 8,
        ],
    ],
    'Daun bawang' => [
        'name' => 'Daun bawang',
        'slug' => 'Daun bawang',
        'humidity' => '60-75%',
        'temperature' => '20-25°C',
        'light' => '55-80%',
        'tds' => '980-1260 ppm',
        'pump' => '4-7 detik',
        'thresholds' => [
            'humidity_min' => 60,
            'humidity_max' => 75,
            'temperature_min' => 20,
            'temperature_max' => 25,
            'light_min' => 55,
            'light_max' => 80,
            'tds_min' => 980,
            'tds_max' => 1260,
            'pump_seconds_min' => 4,
            'pump_seconds_max' => 7,
        ],
    ],
    'Stroberi' => [
        'name' => 'Stroberi',
        'slug' => 'Stroberi',
        'humidity' => '50-70%',
        'temperature' => '18-22°C',
        'light' => '70-90%',
        'tds' => '500-700 ppm',
        'pump' => '5-8 detik',
        'thresholds' => [
            'humidity_min' => 50,
            'humidity_max' => 70,
            'temperature_min' => 18,
            'temperature_max' => 22,
            'light_min' => 70,
            'light_max' => 90,
            'tds_min' => 500,
            'tds_max' => 700,
            'pump_seconds_min' => 5,
            'pump_seconds_max' => 8,
        ],
    ],
];
